description: "The data attributes associated with an NPQ application"
type: object
required:
  - id
  - participant_id
  - full_name
  - email
  - email_validated
  - teacher_reference_number
  - teacher_reference_number_validated
  - eligible_for_funding
  - course_identifier
  - status
properties:
  id:
    type: string
    example: 7a8fef46-3c43-42c0-b3d5-1ba5904ba562
    format: uuid
  participant_id:
    description: "The unique identifier of this NPQ participant"
    type: string
    example: 7a8fef46-3c43-42c0-b3d5-1ba5904ba562
    format: uuid
  full_name:
    description: "The full name of this NPQ participant"
    type: string
    example: "Isabelle MacDonald"
  email:
    description: "The email address registered for this NPQ participant"
    type: string
    example: "isabelle.macdonald2@some-school.example.com"
  email_validated:
    description: "Indicates whether the email address has been validated"
    type: boolean
    example: true
  teacher_reference_number:
    description: "The Teacher Reference Number (TRN) for this NPQ participant"
    type: string
    example: "1234567"
  teacher_reference_number_validated:
    description: "Indicates whether the Teacher Reference Number (TRN) has been validated"
    type: boolean
    example: true
  school_urn:
    description: "The Unique Reference Number (URN) of the school where this NPQ participant is employed"
    type: string
    example: "106286"
  school_ukprn:
    description: "The UK Provider Reference Number (UK Provider Reference Number) of the school where this NPQ participant is employed"
    type: string
    example: "10079319"
  headteacher_status:
    description: "Indicates whether this NPQ participant is or will be a head teacher"
    type: string
    example: "no"
    enum:
      - no
      - yes_when_course_starts
      - yes_in_first_two_years
      - yes_over_two_years
  eligible_for_funding:
    description: "Indicates whether this NPQ participant would be eligible for funding from the DfE"
    type: boolean
    example: true
  funding_choice:
    description: "Indicates how this NPQ participant has said they will funded their training"
    type: string
    example: "trust"
    enum:
      - school
      - trust
      - self
      - another
  course_identifier:
    description: "The Unique Reference Number (URN) of the NPQ course this NPQ application relates to"
    type: string
    example: npq-leading-teaching
    enum:
      - npq-leading-teaching
      - npq-leading-behaviour-culture
      - npq-leading-teaching-development
      - npq-senior-leadership
      - npq-headship
      - npq-executive-leadership
  status:
    description: "The current state of the NPQ application"
    type: string
    example: pending
    enum:
      - pending
      - accepted
      - rejected
