description: "The NPQ Application acceptance request"
type: object
properties:
  schedule_identifier:
    description: "The new schedule of the participant"
    type: string
    enum:
      - npq-aso-march
      - npq-aso-june
      - npq-aso-november
      - npq-aso-december
      - npq-ehco-march
      - npq-ehco-june
      - npq-ehco-november
      - npq-ehco-december
      - npq-leadership-autumn
      - npq-leadership-spring
      - npq-specialist-autumn
      - npq-specialist-spring
    example: npq-leadership-spring
  funded_place:
    description: "Whether the participant has a funded place"
    type: boolean
    example: true
